DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`(
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '用户id',
  `mobile` VARCHAR(11) NOT NULL COMMENT '手机号',
  `pwd` VARCHAR(20) NOT NULL COMMENT '密码',
  `vip` TINYINT DEFAULT 0 COMMENT '用户vip等级',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE (`mobile`)
)AUTO_INCREMENT=101;

DROP TABLE IF EXISTS `user_info`;
CREATE TABLE `user_info`(
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '用户信息id',
  `user_id` INT(11) NOT NULL COMMENT '用户id',
  `nickname` VARCHAR(20) DEFAULT '' COMMENT '昵称',
  `age` TINYINT DEFAULT 0 COMMENT '年龄',
  `sex` TINYINT DEFAULT 0 COMMENT '性别',
  `head` VARCHAR(200) DEFAULT '' COMMENT '头像',
  `interest` VARCHAR(100) DEFAULT '' COMMENT '兴趣',
  `intro` VARCHAR(100) DEFAULT '' COMMENT '自我介绍',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_info_user` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
)AUTO_INCREMENT=101;

DROP TABLE IF EXISTS `question`;
CREATE TABLE `question`(
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '问题id',
  `user_id` INT(11) NOT NULL COMMENT '提问者用户id',
  `title` VARCHAR(100) NOT NULL COMMENT '问题标题',
  `content` VARCHAR(1000) DEFAULT '' COMMENT '问题内容',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_question_user` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
)AUTO_INCREMENT=101;

DROP TABLE IF EXISTS `answer`;
CREATE TABLE `answer`(
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '回答id',
  `user_id` INT(11) NOT NULL COMMENT '回答者用户id',
  `question_id` INT(11) NOT NULL COMMENT '回答问题id',
  `content` VARCHAR(1000) DEFAULT '' COMMENT '回答内容',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_answer_user` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_answer_question` FOREIGN KEY (`question_id`) REFERENCES `question`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
)AUTO_INCREMENT=101;

DROP TABLE IF EXISTS `reply`;
CREATE TABLE `reply`(
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '回复id',
  `user_id` INT(11) NOT NULL COMMENT '回复者用户id',
  `answer_id` INT(11) NOT NULL COMMENT '回答id',
  `content` VARCHAR(100) DEFAULT '' COMMENT '回复内容',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_reply_user` FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_reply_answer` FOREIGN KEY (`answer_id`) REFERENCES `answer`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
)AUTO_INCREMENT=101;